FROM apache/airflow:2.7.3

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
RUN pip install --no-cache-dir streamlit fastapi uvicorn

COPY . /app
WORKDIR /app

ENV AIRFLOW_HOME=/opt/airflow
ENV PYTHONPATH=/app

#ports for Airflow webserver, Streamlit, and FastAPI
EXPOSE 8080 8501 8000